version: "3.7"

services:
  thisrepo-testing:
    image: "indigodatacloud/ci-images:python3.8"
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv/app
    command: >
      sh -c "git config --global --add safe.directory /srv/app &&
             git config --global --add safe.directory /srv/app/TUFSeg &&
             tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /srv/app